{% set name = "theme-material-darcula" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/theme-material-darcula-{{ version }}.tar.gz
  sha256: 0b90dd4fa1a992734955cb5f6e58be37a3989627f85368f9208c70288c4cfcca

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - jupyter_packaging >=0.7.9
    - jupyterlab >=3.0.0
    - nodejs
    - pip
    - setuptools >=40.8.0
  run:
    - python >=3.6
    - jupyterlab >=3.0.0

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/adhadse/theme-material-darcula
  summary: A Jupyterlab theme inspired by JetBrains IDE's Darcula scheme and Material Design.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - adhadse
